import { FormEvent, useEffect, useState } from 'react'
import { apiJson, type AdministrationOptions, type ClassPage, type CourseRunPage, type SchedulePage } from '../../api/client'
import './administration.css'

type Props={csrfToken:string}
type Mode='classes'|'runs'|'schedule'

export function AdministrationWorkspace({csrfToken}:Props){
  const [mode,setMode]=useState<Mode>('classes')
  const [options,setOptions]=useState<AdministrationOptions|null>(null)
  const [classes,setClasses]=useState<ClassPage|null>(null)
  const [runs,setRuns]=useState<CourseRunPage|null>(null)
  const [schedule,setSchedule]=useState<SchedulePage|null>(null)
  const [selectedMeeting,setSelectedMeeting]=useState<number|null>(null)
  const [classPageNumber,setClassPageNumber]=useState(1);const[runPageNumber,setRunPageNumber]=useState(1);const[schedulePageNumber,setSchedulePageNumber]=useState(1)
  const [error,setError]=useState('');const [notice,setNotice]=useState('')
  async function load(){setError('');try{const[o,c,r,s]=await Promise.all([
    apiJson<AdministrationOptions>('/api/administration/options'),
    apiJson<ClassPage>(`/api/administration/classes?page=${classPageNumber}&page_size=50`),
    apiJson<CourseRunPage>(`/api/administration/course-runs?page=${runPageNumber}&page_size=50`),
    apiJson<SchedulePage>(`/api/administration/schedule?page=${schedulePageNumber}&page_size=50`),
  ]);setOptions(o);setClasses(c);setRuns(r);setSchedule(s)}catch(e){setError(e instanceof Error?e.message:'Unable to load administration')}}
  useEffect(()=>{void load()},[classPageNumber,runPageNumber,schedulePageNumber])
  async function post(url:string,body:unknown,method='POST'){setError('');setNotice('');try{await apiJson(url,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify(body)});setNotice('Administration change saved.');await load()}catch(e){setError(e instanceof Error?e.message:'Administration change failed')}}
  return <section><div className="section-heading"><div><p className="eyebrow">Administration</p><h2>Classes and schedule</h2><p>Manage classes, course occurrences, PIC ownership, meetings, and credited sessions.</p></div></div>
    <div className="workspace-tabs" role="tablist"><button className={mode==='classes'?'active':''} onClick={()=>setMode('classes')}>Classes</button><button className={mode==='runs'?'active':''} onClick={()=>setMode('runs')}>Course runs</button><button className={mode==='schedule'?'active':''} onClick={()=>setMode('schedule')}>Schedule</button></div>
    {error&&<p role="alert">{error}</p>}{notice&&<p className="success-notice">{notice}</p>}
    {!options?<p className="notice">Loading administration…</p>:mode==='classes'?<Classes options={options} page={classes} setPage={setClassPageNumber} post={post}/>:mode==='runs'?<Runs options={options} page={runs} setPage={setRunPageNumber} post={post}/>:<Schedule options={options} page={schedule} setPage={setSchedulePageNumber} selectedMeeting={selectedMeeting} setSelectedMeeting={setSelectedMeeting} post={post}/>}</section>
}

function Classes({options,page,setPage,post}:{options:AdministrationOptions;page:ClassPage|null;setPage:(value:number)=>void;post:Post}){
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const employee=Number(d.get('pic_employee_id'));await post('/api/administration/classes',{class_code:d.get('class_code'),display_name:d.get('display_name'),course_id:Number(d.get('course_id')),start_date:d.get('start_date'),capacity:Number(d.get('capacity')),status:d.get('status'),pic_employee_id:employee||null,pic_label:employee?null:d.get('pic_label')})}
  async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const employee=Number(d.get('pic_employee_id'));await post(`/api/administration/cohorts/${d.get('cohort_id')}/pic-assignments`,{pic_employee_id:employee||null,pic_label:employee?null:d.get('pic_label'),start_date:d.get('start_date')})}
  return <><div className="admin-grid"><form className="admin-card" onSubmit={create}><h3>Create class with first course</h3><label>Class code<input name="class_code" defaultValue={options.proposed_class_code} required/></label><label>Display name<input name="display_name" required/></label><OptionSelect label="Course" name="course_id" options={options.courses}/><label>Start date<input name="start_date" type="date" required/></label><label>Capacity<input name="capacity" type="number" min="1" defaultValue="12" required/></label><label>Initial status<select name="status"><option value="active">Active</option><option value="planned">Planned</option></select></label><label>PIC employee (optional)<select name="pic_employee_id"><option value="">Use team label</option>{options.employees.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label>PIC team label<input name="pic_label" list="pic-labels"/><datalist id="pic-labels">{options.pic_labels.map(x=><option key={x}>{x}</option>)}</datalist></label><button>Create class</button></form>
    <form className="admin-card" onSubmit={assign}><h3>Assign new PIC</h3><OptionSelect label="Class" name="cohort_id" options={options.cohorts}/><label>Start date<input name="start_date" type="date" required/></label><label>PIC employee (optional)<select name="pic_employee_id"><option value="">Use team label</option>{options.employees.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label>PIC team label<input name="pic_label"/></label><button>Assign PIC</button></form></div>
    <div className="table-wrap"><table><thead><tr><th>Class</th><th>Status</th><th>Capacity</th><th>Current PIC</th><th>Course runs</th></tr></thead><tbody>{page?.items.map(x=><tr key={x.cohort_id}><td><strong>{x.class_code}</strong><small>{x.display_name}</small></td><td><span className="badge">{x.status}</span></td><td>{x.capacity??'—'}</td><td>{x.current_pic??'—'}</td><td>{x.course_run_count}</td></tr>)}</tbody></table></div><AdminPagination page={page} setPage={setPage}/></>
}

function Runs({options,page,setPage,post}:{options:AdministrationOptions;page:CourseRunPage|null;setPage:(value:number)=>void;post:Post}){
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await post(`/api/administration/cohorts/${d.get('cohort_id')}/course-runs`,{course_id:Number(d.get('course_id')),start_date:d.get('start_date')})}
  async function status(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await post(`/api/administration/course-runs/${d.get('course_run_id')}/status`,{status:d.get('status'),end_date:d.get('end_date')||null})}
  return <><div className="admin-grid"><form className="admin-card" onSubmit={create}><h3>Add course run</h3><OptionSelect label="Class" name="cohort_id" options={options.cohorts}/><OptionSelect label="Course" name="course_id" options={options.courses}/><label>Start date<input name="start_date" type="date" required/></label><button>Add course run</button></form><form className="admin-card" onSubmit={status}><h3>Change run lifecycle</h3><OptionSelect label="Class and course" name="course_run_id" options={options.course_runs}/><label>New status<select name="status"><option>active</option><option>completed</option><option>cancelled</option><option>archived</option></select></label><label>End date (when applicable)<input name="end_date" type="date"/></label><button>Update status</button></form></div>
    <div className="table-wrap"><table><thead><tr><th>Class / course</th><th>Run</th><th>Status</th><th>Dates</th><th>Next session</th></tr></thead><tbody>{page?.items.map(x=><tr key={x.course_run_id}><td><strong>{x.class_code} · {x.course_code}</strong><small>{x.course_name}</small></td><td>{x.run_number}</td><td><span className="badge">{x.status}</span></td><td>{x.start_date??'—'}<small>{x.end_date?`Ends ${x.end_date}`:''}</small></td><td>{x.next_sequence_in_run}</td></tr>)}</tbody></table></div><AdminPagination page={page} setPage={setPage}/></>
}

function Schedule({options,page,setPage,selectedMeeting,setSelectedMeeting,post}:{options:AdministrationOptions;page:SchedulePage|null;setPage:(value:number)=>void;selectedMeeting:number|null;setSelectedMeeting:(x:number|null)=>void;post:Post}){
  const meeting=page?.items.find(x=>x.meeting_id===selectedMeeting)
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await post(`/api/administration/course-runs/${d.get('course_run_id')}/meetings`,{starts_at:new Date(String(d.get('starts_at'))).toISOString(),duration_minutes:Number(d.get('duration_minutes')),first_sequence_in_run:Number(d.get('first_sequence_in_run')),unit_count:Number(d.get('unit_count')),unit_type:d.get('unit_type'),status:d.get('status')})}
  async function correct(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!meeting)return;const d=new FormData(e.currentTarget);await post(`/api/administration/meetings/${meeting.meeting_id}`,{course_run_id:meeting.course_run_id,starts_at:new Date(String(d.get('starts_at'))).toISOString(),duration_minutes:Number(d.get('duration_minutes')),status:d.get('status'),reason:d.get('reason')||null},'PATCH')}
  async function cancel(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!meeting)return;const d=new FormData(e.currentTarget);await post(`/api/administration/meetings/${meeting.meeting_id}/cancellation`,{reason:d.get('reason')})}
  async function addUnits(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!meeting)return;const d=new FormData(e.currentTarget);await post(`/api/administration/meetings/${meeting.meeting_id}/session-units`,{course_run_id:meeting.course_run_id,first_sequence_in_run:Number(d.get('first_sequence_in_run')),unit_count:Number(d.get('unit_count')),unit_type:d.get('unit_type')})}
  return <><form className="admin-card schedule-create" onSubmit={create}><h3>Create meeting and credited sessions</h3><OptionSelect label="Class and course" name="course_run_id" options={options.course_runs}/><label>Meeting start<input name="starts_at" type="datetime-local" required/></label><label>Duration minutes<input name="duration_minutes" type="number" min="1" defaultValue="120" required/></label><label>First session number<input name="first_sequence_in_run" type="number" min="1" required/></label><label>Sessions counted<select name="unit_count"><option value="1">1</option><option value="2">2</option></select></label><label>Session type<select name="unit_type"><option value="normal">Normal</option><option value="final_test">Final test</option><option value="makeup">Make-up</option><option value="admin">Administrative</option></select></label><label>Meeting status<select name="status"><option value="planned">Planned</option><option value="completed">Completed</option></select></label><button>Create meeting</button></form>
    <label className="meeting-picker">Meeting to revise<select value={selectedMeeting??''} onChange={e=>setSelectedMeeting(e.target.value?Number(e.target.value):null)}><option value="">Select meeting</option>{page?.items.filter(x=>x.status!=='cancelled').map(x=><option key={x.meeting_id} value={x.meeting_id}>{x.class_code} · {x.course_code} · {new Date(x.starts_at).toLocaleString()}</option>)}</select></label>
    {meeting&&<div className="admin-grid"><form className="admin-card" onSubmit={correct}><h3>Correct meeting</h3><label>Meeting start<input name="starts_at" type="datetime-local" defaultValue={localDateTimeValue(meeting.starts_at)} required/></label><label>Duration minutes<input name="duration_minutes" type="number" min="1" defaultValue={meeting.duration_minutes} required/></label><label>Status<select name="status" defaultValue={meeting.status}><option value="planned">Planned</option><option value="completed">Completed</option></select></label><label>Schedule change reason<input name="reason"/></label><button>Save correction</button></form><form className="admin-card" onSubmit={addUnits}><h3>Add credited sessions</h3><label>First session number<input name="first_sequence_in_run" type="number" min="1" required/></label><label>Sessions to add<select name="unit_count"><option value="1">1</option><option value="2">2</option></select></label><label>Session type<select name="unit_type"><option value="normal">Normal</option><option value="final_test">Final test</option><option value="makeup">Make-up</option><option value="admin">Administrative</option></select></label><button>Add sessions</button></form><form className="admin-card danger-card" onSubmit={cancel}><h3>Cancel meeting</h3><label>Cancellation reason<input name="reason" required/></label><button>Cancel meeting</button></form></div>}
    <div className="table-wrap"><table><thead><tr><th>Class / course</th><th>Starts</th><th>Meeting</th><th>Credited sessions</th></tr></thead><tbody>{page?.items.map(x=><tr key={x.meeting_id}><td><strong>{x.class_code} · {x.course_code}</strong><small>Run {x.run_number}</small></td><td>{new Date(x.starts_at).toLocaleString()}</td><td>{x.duration_minutes} min · <span className="badge">{x.status}</span><small>{x.cancellation_reason}</small></td><td>{x.units.map(u=>`${u.sequence_in_run} (${u.unit_type})`).join(', ')||'None'}</td></tr>)}</tbody></table></div><AdminPagination page={page} setPage={setPage}/></>
}

type Post=(url:string,body:unknown,method?:string)=>Promise<void>
function OptionSelect({label,name,options}:{label:string;name:string;options:{id:number;label:string}[]}){return <label>{label}<select name={name} required><option value="">Select</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>}
function AdminPagination({page,setPage}:{page:{page:number;page_size:number;total:number}|null;setPage:(value:number)=>void}){if(!page)return null;return <div className="pagination"><span>Page {page.page} · {page.total} item(s)</span><button className="secondary" disabled={page.page===1} onClick={()=>setPage(page.page-1)}>Previous</button><button className="secondary" disabled={page.page*page.page_size>=page.total} onClick={()=>setPage(page.page+1)}>Next</button></div>}
function localDateTimeValue(value:string){const date=new Date(value);const localTime=date.getTime()-date.getTimezoneOffset()*60_000;return new Date(localTime).toISOString().slice(0,16)}
