/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learners */
        get: operations["learners_api_learners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learners/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learner Detail */
        get: operations["learner_detail_api_learners__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationSummary */
        ApplicationSummary: {
            /** Active Employees */
            active_employees: number;
            /** Active Learners */
            active_learners: number;
            /** High Issues */
            high_issues: number;
            /** Open Course Runs */
            open_course_runs: number;
            /** Open Quality Issues */
            open_quality_issues: number;
            /** Operational Issues */
            operational_issues: number;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["PublicUser"];
        };
        /** CourseHistoryItem */
        CourseHistoryItem: {
            /** Attendance Ratio */
            attendance_ratio?: number | null;
            /** Class Code */
            class_code: string;
            /** Course Name */
            course_name: string;
            /** Final Level */
            final_level?: string | null;
            /** Passed */
            passed?: boolean | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Start Session Number */
            start_session_number: number;
            /** Status */
            status: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            hr_home: components["schemas"]["HrHomeSummary"] | null;
            summary: components["schemas"]["ApplicationSummary"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HrHomeSummary */
        HrHomeSummary: {
            /** Active People */
            active_people: number;
            /** Current Learners */
            current_learners: number;
            /** Follow Ups */
            follow_ups: number;
            /** Open Classes */
            open_classes: number;
            /** Review Items */
            review_items: number;
            /** Urgent Items */
            urgent_items: number;
        };
        /** LearnerAuditItem */
        LearnerAuditItem: {
            /** Action */
            action: string;
            /** Actor Username */
            actor_username: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LearnerDetail */
        LearnerDetail: {
            /** Audit Summary */
            audit_summary: components["schemas"]["LearnerAuditItem"][];
            /** Course History */
            course_history: components["schemas"]["CourseHistoryItem"][];
            learner: components["schemas"]["LearnerJourney"];
        };
        /** LearnerJourney */
        LearnerJourney: {
            /** Active Class Code */
            active_class_code?: string | null;
            /** Active Cohort Id */
            active_cohort_id?: number | null;
            /** Active Course Name */
            active_course_name?: string | null;
            /** Active Course Run Id */
            active_course_run_id?: number | null;
            /** Active Enrollment Id */
            active_enrollment_id?: number | null;
            /** Active Membership Id */
            active_membership_id?: number | null;
            /** Business Unit Id */
            business_unit_id?: number | null;
            /** Business Unit Name */
            business_unit_name?: string | null;
            /** Emp Code */
            emp_code: string;
            /** Employee Id */
            employee_id: number;
            /** Employment Status */
            employment_status: string;
            /** Entrance Level */
            entrance_level?: string | null;
            /** Entrance Level Id */
            entrance_level_id?: number | null;
            /** Full Name */
            full_name: string;
            /** Job Role Id */
            job_role_id?: number | null;
            /** Job Role Name */
            job_role_name?: string | null;
            /** Latest Class Code */
            latest_class_code?: string | null;
            /** Latest Course Name */
            latest_course_name?: string | null;
            /** Latest Enrollment Status */
            latest_enrollment_status?: string | null;
            /** Lifecycle */
            lifecycle: string;
            /** Membership Class Code */
            membership_class_code?: string | null;
            /** Membership Cohort Id */
            membership_cohort_id?: number | null;
            /** Membership Count */
            membership_count: number;
            /** Placement Id */
            placement_id?: number | null;
        };
        /** LearnerListItem */
        LearnerListItem: {
            /** Attendance Ratio */
            attendance_ratio?: number | null;
            /** Business Unit Name */
            business_unit_name?: string | null;
            /** Class Code */
            class_code?: string | null;
            /** Course Code */
            course_code?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Emp Code */
            emp_code: string;
            /** Employee Id */
            employee_id: number;
            /** Employment Status */
            employment_status: string;
            /** Enrollment Status */
            enrollment_status?: string | null;
            /** Entrance Level */
            entrance_level?: string | null;
            /** Full Name */
            full_name: string;
            /** Job Role Name */
            job_role_name?: string | null;
            /** Pic */
            pic?: string | null;
        };
        /** LearnerPage */
        LearnerPage: {
            /** Items */
            items: components["schemas"]["LearnerListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Sort
             * @default full_name_asc_emp_code_asc
             */
            sort: string;
            /** Total */
            total: number;
        };
        /** LoginBody */
        LoginBody: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** PublicUser */
        PublicUser: {
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "editor" | "viewer";
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                english_class_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                english_class_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                english_class_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    learners_api_learners_get: {
        parameters: {
            query?: {
                q?: string;
                learning_status?: "all" | "current" | "not_current";
                class_code?: string | null;
                course?: string | null;
                pic?: string | null;
                business_unit?: string | null;
                job_role?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                english_class_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    learner_detail_api_learners__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: {
                english_class_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
