import { expect, test } from '@playwright/test'

test('admin completes follow-up, class schedule, report, and audit journeys',async({page})=>{
  await page.goto('/')
  await page.getByLabel('Username').fill('pytest_admin')
  await page.getByLabel('Password').fill('admin-pass')
  await page.getByRole('button',{name:'Sign in'}).click()

  await page.getByRole('button',{name:'Follow-ups'}).click()
  await page.getByRole('button',{name:'Logged issues'}).click()
  await expect(page.getByText('playwright_followup')).toBeVisible()
  await page.getByLabel('Resolution note').fill('Browser owner verification')
  await page.getByRole('button',{name:'Save resolution'}).click()
  await expect(page.getByText('Follow-up action saved.')).toBeVisible()
  await page.getByRole('button',{name:'Approved actions'}).click()
  for(const heading of ['Backfill unknown organization','Backfill unknown entrance placement','Approve legacy attendance exception','Cancel duplicate schedule occurrence']){
    await expect(page.getByRole('heading',{name:heading})).toBeVisible()
  }

  await page.getByRole('button',{name:'Classes & schedule'}).click()
  const classForm=page.getByRole('heading',{name:'Create class with first course'}).locator('..')
  await classForm.getByLabel('Class code').fill('PW900')
  await classForm.getByLabel('Display name').fill('Playwright Administration')
  await classForm.getByLabel('Course').selectOption({index:1})
  await classForm.getByLabel('Start date').fill('2030-10-01')
  await classForm.getByLabel('PIC team label').fill('Playwright Team')
  await classForm.getByRole('button',{name:'Create class'}).click()
  await expect(page.getByText('Administration change saved.')).toBeVisible()
  await expect(page.getByText('PW900',{exact:true})).toBeVisible()

  await page.getByRole('button',{name:'Schedule',exact:true}).click()
  const runSelect=page.getByLabel('Class and course')
  const runValue=await runSelect.locator('option',{hasText:'PW900'}).getAttribute('value')
  await runSelect.selectOption(runValue!)
  await page.getByLabel('Meeting start').fill('2030-10-03T09:00')
  await page.getByLabel('First session number').fill('1')
  await page.getByLabel('Sessions counted').selectOption('2')
  await page.getByRole('button',{name:'Create meeting'}).click()
  await expect(page.getByText('Administration change saved.')).toBeVisible()
  const meetingSelect=page.getByLabel('Meeting to revise')
  const meetingValue=await meetingSelect.locator('option',{hasText:'PW900'}).getAttribute('value')
  await meetingSelect.selectOption(meetingValue!)
  await expect(page.getByLabel('Meeting start').nth(1)).toHaveValue('2030-10-03T09:00')
  await page.getByLabel('Duration minutes').nth(1).fill('90')
  await page.getByLabel('Schedule change reason').fill('Browser schedule correction')
  await page.getByRole('button',{name:'Save correction'}).click()
  await expect(page.getByText('Administration change saved.')).toBeVisible()
  await page.getByLabel('Cancellation reason').fill('Browser owner cancellation')
  await page.getByRole('button',{name:'Cancel meeting'}).click()
  await expect(page.getByText('Browser owner cancellation')).toBeVisible()

  await page.getByRole('button',{name:'Reports'}).click()
  await expect(page.getByLabel('Registered report')).toBeVisible()
  await expect(page.locator('table tbody tr').first()).toBeVisible()
  await page.getByRole('button',{name:'Audit history'}).click()
  await page.getByLabel('Action').fill('meeting.cancel')
  await page.getByRole('button',{name:'Filter audit'}).click()
  await expect(page.getByText('meeting.cancel')).toBeVisible()
  await expect(page.getByText('pytest_admin')).toBeVisible()
})

test('viewer can run reports but cannot infer audit access',async({page})=>{
  await page.goto('/')
  await page.getByLabel('Username').fill('pytest_viewer')
  await page.getByLabel('Password').fill('viewer-pass')
  await page.getByRole('button',{name:'Sign in'}).click()
  await page.getByRole('button',{name:'Reports'}).click()
  await expect(page.getByLabel('Registered report')).toBeVisible()
  await expect(page.getByRole('button',{name:'Audit history'})).toHaveCount(0)
})
