import { expect, test } from '@playwright/test'

test('admin edits a profile and starts a learner without a full page reload', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Username').fill('pytest_admin')
  await page.getByLabel('Password').fill('admin-pass')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await expect(page.getByRole('heading', { name: 'HR home' })).toBeVisible()
  await page.getByRole('button', { name: 'Learners' }).click()
  await page.getByLabel('Search by employee code or name').fill('Directory Alpha')
  await page.getByRole('button', { name: 'Search' }).click()
  await page.getByRole('button', { name: /Directory Alpha/ }).click()

  await expect(page.getByRole('heading', { name: 'Directory Alpha' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Course history' })).toBeVisible()
  await expect(page.getByText('learner.onboard')).toBeVisible()
  await page.getByRole('button', { name: 'Edit profile' }).click()
  await page.getByLabel('Full name').fill('Directory Alpha Updated')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('heading', { name: 'Directory Alpha Updated' })).toBeVisible()
  await expect(page.getByText('Profile saved.')).toBeVisible()
  await expect(page.getByText('employee.upsert')).toBeVisible()

  await page.getByRole('button', { name: /Back to learners/ }).click()
  await page.getByRole('button', { name: 'Start learner' }).click()
  await page.getByLabel('Employee code').fill('PW-START-001')
  await page.getByLabel('Full name').fill('Playwright Start Learner')
  await page.getByLabel('Business unit').selectOption({ index: 1 })
  await page.getByLabel('Role').selectOption({ index: 1 })
  await page.getByLabel('Entrance level').selectOption({ index: 1 })
  await page.getByLabel('Destination').selectOption({ index: 1 })
  await page.getByLabel('Join date').fill('2026-08-03')
  await expect(page.getByText(/First applicable session:/)).toBeVisible()
  await expect(page.getByText(/Projected class size:/)).toBeVisible()
  const overrideReason = page.getByLabel('Capacity override reason')
  if (await overrideReason.isVisible()) await overrideReason.fill('Playwright approved overflow')
  await page.getByRole('button', { name: 'Confirm start' }).click()
  await expect(page.getByRole('heading', { name: 'Playwright Start Learner' })).toBeVisible()
  await expect(page.getByText('Learning started.')).toBeVisible()
  await expect(page.getByText('learner.onboard')).toBeVisible()

  await page.getByRole('button', { name: 'Transfer learner' }).click()
  await page.getByLabel('Target class and course').selectOption({ index: 1 })
  await page.getByLabel('Transfer date').fill('2026-08-15')
  await expect(page.getByText(/First applicable session:/)).toBeVisible()
  await expect(page.getByText(/Projected class size:/)).toBeVisible()
  const transferOverrideReason = page.getByLabel('Capacity override reason')
  if (await transferOverrideReason.isVisible()) await transferOverrideReason.fill('Playwright approved transfer seat')
  await page.getByRole('button', { name: 'Confirm transfer' }).click()
  await expect(page.getByText('Learner transferred.')).toBeVisible()
  await expect(page.getByText('learner.transfer')).toBeVisible()
})

test('viewer sees the approved summary but no HR learner navigation', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Username').fill('pytest_viewer')
  await page.getByLabel('Password').fill('viewer-pass')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await expect(page.getByRole('heading', { name: 'Workspace summary' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Learners' })).toHaveCount(0)
})
