import { expect, test } from '@playwright/test'

test('admin edits a profile and starts a learner without a full page reload', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Username').fill('pytest_admin')
  await page.getByLabel('Password').fill('admin-pass')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await expect(page.getByRole('heading', { name: 'HR home' })).toBeVisible()
  await page.getByRole('button', { name: 'Learners' }).click()
  await page.getByLabel('Search by employee code or name').fill('Directory Alpha')
  await page.getByRole('button', { name: 'Search' }).click()
  await page.getByRole('button', { name: /Directory Alpha/ }).click()

  await expect(page.getByRole('heading', { name: 'Directory Alpha' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Course history' })).toBeVisible()
  await expect(page.getByText('learner.onboard')).toBeVisible()
  await page.getByRole('button', { name: 'Edit profile' }).click()
  await page.getByLabel('Full name').fill('Directory Alpha Updated')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('heading', { name: 'Directory Alpha Updated' })).toBeVisible()
  await expect(page.getByText('Profile saved.')).toBeVisible()
  await expect(page.getByText('employee.upsert')).toBeVisible()

  await page.getByRole('button', { name: /Back to learners/ }).click()
  await page.getByRole('button', { name: 'Start learner' }).click()
  await page.getByLabel('Employee code').fill('PW-START-001')
  await page.getByLabel('Full name').fill('Playwright Start Learner')
  await page.getByLabel('Business unit').selectOption({ index: 1 })
  await page.getByLabel('Role').selectOption({ index: 1 })
  await page.getByLabel('Entrance level').selectOption({ index: 1 })
  await page.getByLabel('Destination').selectOption({ index: 1 })
  await page.getByLabel('Join date').fill('2026-08-03')
  await expect(page.getByText(/First applicable session:/)).toBeVisible()
  await expect(page.getByText(/Projected class size:/)).toBeVisible()
  const overrideReason = page.getByLabel('Capacity override reason')
  if (await overrideReason.isVisible()) await overrideReason.fill('Playwright approved overflow')
  await page.getByRole('button', { name: 'Confirm start' }).click()
  await expect(page.getByRole('heading', { name: 'Playwright Start Learner' })).toBeVisible()
  await expect(page.getByText('Learning started.')).toBeVisible()
  await expect(page.getByText('learner.onboard')).toBeVisible()

  await page.getByRole('button', { name: 'Transfer learner' }).click()
  await page.getByLabel('Target class and course').selectOption({ index: 1 })
  await page.getByLabel('Transfer date').fill('2026-08-15')
  await expect(page.getByText(/First applicable session:/)).toBeVisible()
  await expect(page.getByText(/Projected class size:/)).toBeVisible()
  const transferOverrideReason = page.getByLabel('Capacity override reason')
  if (await transferOverrideReason.isVisible()) await transferOverrideReason.fill('Playwright approved transfer seat')
  await page.getByRole('button', { name: 'Confirm transfer' }).click()
  await expect(page.getByText('Learner transferred.')).toBeVisible()
  await expect(page.getByText('learner.transfer')).toBeVisible()

  await page.getByRole('button', { name: 'Attendance' }).click()
  await page.getByLabel('Class and course').selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Create session' }).click()
  await page.getByLabel('Session start').fill('2030-09-01T09:00')
  await page.getByRole('button', { name: 'Confirm session' }).click()
  await expect(page.getByRole('button', { name: 'Save attendance' })).toBeEnabled()
  await page.locator('select[id^="attendance-"]').first().selectOption('Absent')
  await page.getByRole('button', { name: 'Save attendance' }).click()
  await expect(page.getByText('Attendance saved.')).toBeVisible()
  await expect(page.locator('.attendance-summary').getByText('Completed', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Record make-up' }).click()
  await page.getByLabel('Original absence').selectOption({ index: 1 })
  await page.getByLabel('Make-up session').selectOption({ index: 1 })
  await page.getByLabel('Reason').fill('Playwright approved recovery class')
  await expect(page.getByText('Original attendance remains Absent.')).toBeVisible()
  await expect(page.getByText('Adds 0 denominator units.')).toBeVisible()
  await page.getByRole('button', { name: 'Confirm make-up credit' }).click()
  await expect(page.getByText('Make-up attendance credited.')).toBeVisible()
  await expect(page.getByText('No eligible absences currently have a make-up session available.')).toBeVisible()

  await page.getByRole('button', { name: 'Final results' }).click()
  await page.getByLabel('Learner and course').selectOption({ index: 1 })
  await expect(page.getByText(/attendance$/)).toBeVisible()
  await page.getByLabel('Final level').selectOption({ index: 1 })
  await page.getByLabel('Passed').check()
  await page.getByLabel('Next course').selectOption({ index: 1 })
  await page.getByLabel('Teacher notes').fill('Playwright final assessment')
  await page.getByRole('button', { name: 'Save final result' }).click()
  await expect(page.getByText('Final result saved as version 1.')).toBeVisible()

  await page.getByLabel('Eligibility decision').selectOption('true')
  await page.getByLabel('Override reason').fill('Playwright approved exception')
  await page.getByRole('button', { name: 'Save eligibility override' }).click()
  await expect(page.getByText('Eligibility override saved.')).toBeVisible()
  await expect(page.getByText('Admin override')).toBeVisible()

  await page.getByLabel('Completion action').selectOption('suggest')
  await page.getByRole('button', { name: 'Apply completion action' }).click()
  await expect(page.getByText('Completion suggested.')).toBeVisible()
  await page.getByLabel('Completion action').selectOption('confirm')
  await page.getByRole('button', { name: 'Apply completion action' }).click()
  await expect(page.getByText('Completion confirmed.')).toBeVisible()

  await page.getByRole('button', { name: 'Monthly review' }).click()
  await page.getByLabel('Review month').fill('2026-08')
  await expect(page.locator('.monthly-summary strong').first()).toContainText('active participants')
  await page.getByRole('button', { name: 'Summary & export' }).click()
  await page.getByLabel('Highlights').fill('Playwright monthly highlight')
  await page.getByLabel('Risks').fill('Playwright monthly risk')
  await page.getByLabel('Next-month priorities').fill('Playwright monthly priority')
  await page.getByRole('button', { name: 'Save action summary' }).click()
  await expect(page.getByText(/Action summary saved as version \d+\./)).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download Excel review' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('english-class-monthly-review-2026-08-01.xlsx')
})

test('viewer sees the approved summary but no HR learner navigation', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Username').fill('pytest_viewer')
  await page.getByLabel('Password').fill('viewer-pass')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await expect(page.getByRole('heading', { name: 'Workspace summary' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Learners' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Final results' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Monthly review' })).toHaveCount(0)
})
